spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/accounting_firm
    username: postgres
    password: postgres
  jpa:
    show-sql: true

app:
  cookie:
    secure: false
  frontend-url: http://localhost:4200

logging:
  level:
    com.gwhaitech: DEBUG
    org.springframework.security: DEBUG
